/**
 * Generates src/tokens.css from the platform-neutral token source in tokens/.
 * Web reads the generated CSS. A future native app reads the same JSON.
 * Nobody hand-writes a colour, a duration, or a type size twice. (R24.2)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (f) => JSON.parse(readFileSync(join(root, "tokens", f), "utf8"));

const colour = read("color.json");
const scale = read("scale.json");
const density = read("density.json");

/** Resolve "{ink.600}" against the ramps. Literal values pass through. */
const resolve = (v) => {
  const m = /^\{([a-z]+)\.(\d+)\}$/.exec(v);
  if (!m) return v;
  const ramp = colour.ramps[m[1]];
  if (!ramp || !ramp[m[2]]) throw new Error(`Unknown ramp reference: ${v}`);
  return `var(--${m[1]}-${m[2]})`;
};

const out = [];
const w = (s = "") => out.push(s);
const skip = (k) => k.startsWith("$");

w(`/* Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit by hand. */`);
w(`@import "tailwindcss";`);
w();

/* ---------- ramps and spectrum ---------- */
w(`:root {`);
w(`  /* Ramps. Warm stone canvas, ink for action, ember for warmth. */`);
for (const [name, steps] of Object.entries(colour.ramps))
  for (const [step, value] of Object.entries(steps)) w(`  --${name}-${step}: ${value};`);
w();
w(`  /* Spectrum. Twelve hues, matched lightness and chroma. Colour as data. */`);
for (const [hue, steps] of Object.entries(colour.spectrum)) {
  if (skip(hue)) continue;
  for (const [step, value] of Object.entries(steps)) w(`  --hue-${hue}-${step}: ${value};`);
}
w();
w(`  /* Status. One meaning each. A spectrum hue never signals success or danger. */`);
for (const [name, v] of Object.entries(colour.status)) {
  w(`  --${name}: ${v.base};`);
  w(`  --${name}-soft: ${v.soft};`);
  w(`  --${name}-text: ${v.text};`);
}
w();
w(`  /* Semantic, light. Components reference only these. */`);
for (const [k, v] of Object.entries(colour.semantic.light)) w(`  --${k}: ${resolve(v)};`);
w(`}`);
w();

/* ---------- dark ---------- */
const darkBody = Object.entries(colour.semantic.dark).map(([k, v]) => `    --${k}: ${resolve(v)};`);
const darkStatus = Object.entries(colour.status).flatMap(([name, v]) => {
  const dark = v.dark ?? {};
  return [
    `    --${name}: ${dark.base ?? v.base};`,
    `    --${name}-soft: ${dark.soft ?? v.soft};`,
    `    --${name}-text: ${dark.text ?? v.text};`,
  ];
});

const darkSpectrum = [
  `    /* Hue pairs for dark: tint an area with 900, key text to 100. */`,
  ...Object.keys(colour.spectrum).filter((h) => !skip(h)).flatMap((h) => [
    `    --hue-${h}-tint: var(--hue-${h}-900);`,
    `    --hue-${h}-key: var(--hue-${h}-100);`,
  ]),
];
const lightSpectrumPairs = Object.keys(colour.spectrum).filter((h) => !skip(h)).flatMap((h) => [
  `  --hue-${h}-tint: var(--hue-${h}-100);`,
  `  --hue-${h}-key: var(--hue-${h}-700);`,
]);
w(`:root {`);
w(`  /* Light hue pairs: tint an area with 100, key text to 700. */`);
lightSpectrumPairs.forEach(w);
w(`}`);
w();

/* The light palette again, on any element rather than the root alone, so a
   subtree can hold itself to light while the rest of the page follows the
   reader. Every public page does: a church deciding whether to trust us reads
   the same page as the church next door, in the colours the design draws. */
w(`[data-theme="light"] {`);
w(`  color-scheme: light;`);
for (const [name, v] of Object.entries(colour.status)) {
  w(`  --${name}: ${v.base};`);
  w(`  --${name}-soft: ${v.soft};`);
  w(`  --${name}-text: ${v.text};`);
}
for (const [k, v] of Object.entries(colour.semantic.light)) w(`  --${k}: ${resolve(v)};`);
lightSpectrumPairs.forEach(w);
w(`}`);
w();
w(`@media (prefers-color-scheme: dark) {`);
w(`  :root:not([data-theme="light"]) {`);
darkBody.forEach(w);
darkStatus.forEach(w);
darkSpectrum.forEach(w);
w(`  }`);
w(`}`);
w();
/* The dark palette on any element rather than the root alone, which is what
   the light block above has always done. ConnectApp's own website opens dark
   while a church's screens follow the reader, and that is a subtree holding
   itself to a theme, so the two have to be written the same way. */
w(`[data-theme="dark"] {`);
darkBody.forEach(w);
darkStatus.forEach(w);
darkSpectrum.forEach(w);
w(`}`);
w();

/* ---------- density ---------- */
w(`/* Density. One system, three modes. Set data-density on the root element, or on
   any element whose subtree runs at a different one: a kiosk inside the app is
   station density while the page around it stays office. */`);
const emitDensity = (sel, mode) => {
  w(`${sel} {`);
  for (const [k, v] of Object.entries(mode)) { if (skip(k)) continue; w(`  --d-${k}: ${v};`); }
  w(`}`);
};
emitDensity(`:root, [data-density="office"]`, density.modes.office);
w();
emitDensity(`[data-density="station"]`, density.modes.station);
w();
emitDensity(`[data-density="portal"]`, density.modes.portal);
w();

/* ---------- Tailwind theme ---------- */
w(`@theme inline {`);
w(`  /* Colours as utilities: bg-canvas, text-fg-muted, border-line, bg-hue-teal-100. */`);
for (const [name, steps] of Object.entries(colour.ramps))
  for (const step of Object.keys(steps)) w(`  --color-${name}-${step}: var(--${name}-${step});`);
for (const [hue, steps] of Object.entries(colour.spectrum)) {
  if (skip(hue)) continue;
  for (const step of Object.keys(steps)) w(`  --color-hue-${hue}-${step}: var(--hue-${hue}-${step});`);
  w(`  --color-hue-${hue}-tint: var(--hue-${hue}-tint);`);
  w(`  --color-hue-${hue}-key: var(--hue-${hue}-key);`);
}
for (const name of Object.keys(colour.status)) {
  w(`  --color-${name}: var(--${name});`);
  w(`  --color-${name}-soft: var(--${name}-soft);`);
  w(`  --color-${name}-text: var(--${name}-text);`);
}
for (const k of Object.keys(colour.semantic.light)) w(`  --color-${k}: var(--${k});`);
w();
w(`  /* Faces. Display serif for hierarchy, sans for work, mono for codes read aloud. */`);
w(`  --font-display: var(--font-fraunces), Georgia, "Times New Roman", serif;`);
w(`  --font-sans: var(--font-inter), ui-sans-serif, system-ui, sans-serif;`);
w(`  --font-mono: var(--font-jetbrains), ui-monospace, "SF Mono", monospace;`);
w();
w(`  /* Type scale. Never lighter than 400 for body. */`);
for (const [name, t] of Object.entries(scale.type)) {
  w(`  --text-${name}: ${t.size};`);
  w(`  --text-${name}--line-height: ${t.leading};`);
  w(`  --text-${name}--font-weight: ${t.weight};`);
  w(`  --text-${name}--letter-spacing: ${t.tracking};`);
}
w();
w(`  /* Radius. Larger surfaces, larger radius. Pills for badges only. */`);
for (const [k, v] of Object.entries(scale.radius)) w(`  --radius-${k}: ${v};`);
w();
w(`  /* Elevation. A hairline does the work, the shadow hints. No blur, ever. */`);
for (const [k, v] of Object.entries(scale.elevation)) w(`  --shadow-${k}: ${v};`);
w();
w(`  /* Motion. Exits are faster than entrances. */`);
for (const [k, v] of Object.entries(scale.motion.duration)) w(`  --duration-${k}: ${v};`);
for (const [k, v] of Object.entries(scale.motion.ease)) w(`  --ease-${k}: ${v};`);
w(`}`);
w();

/* ---------- base ---------- */
w(`@layer base {
  * { border-color: var(--line); }

  /* Entrances. Exits are faster, and reduced motion flattens both. */
  @keyframes connectapp-fade { from { opacity: 0; } to { opacity: 1; } }
  @keyframes connectapp-slide-in { from { transform: translateX(100%); } to { transform: translateX(0); } }
  @keyframes connectapp-pop { from { opacity: 0; scale: 0.97; } to { opacity: 1; scale: 1; } }
  @keyframes connectapp-rise { from { opacity: 0; translate: 0 4px; } to { opacity: 1; translate: 0 0; } }
  @keyframes connectapp-shake {
    0%, 100% { translate: 0 0; }
    20% { translate: -5px 0; }
    45% { translate: 4px 0; }
    70% { translate: -2px 0; }
  }

  html {
    -webkit-text-size-adjust: 100%;
    color-scheme: light dark;
  }

  body {
    background-color: var(--canvas);
    color: var(--fg);
    font-family: var(--font-sans), ui-sans-serif, system-ui, sans-serif;
    font-size: var(--d-text-body);
    line-height: var(--d-leading-body);
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }

  /* A subtree at its own density reads at that density. body computes its size
     from the root, and everything under it inherits that number rather than
     re-resolving the variable, so without this a portal screen inside an office
     page sets its inputs at 16px and everything it did not name at 14px. The
     root is left alone: a size in rem on html redefines what rem means. */
  [data-density]:not(html) {
    font-size: var(--d-text-body);
    line-height: var(--d-leading-body);
  }

  /* Tabular figures everywhere a number is compared to another number. */
  table, [data-numeric] { font-variant-numeric: tabular-nums; }

  /* Lucide at 1.75, which is the weight the redesign draws every icon at. A CSS
     property beats the attribute the library writes, so this reaches all of
     them without a prop on every call site. */
  svg.lucide { stroke-width: 1.75; }

  /* A focus ring that is never removed, in any state, for any reason. (R24.15) */
  :focus-visible {
    outline: 2px solid var(--ring);
    outline-offset: 2px;
    border-radius: var(--radius-sm);
  }

  ::selection { background: var(--selection); color: var(--fg); }

  /* Reduced motion means no motion, not less. One override, so no component can forget. (R24.13) */
  @media (prefers-reduced-motion: reduce) {
    :root {
      --duration-instant: 1ms; --duration-fast: 1ms; --duration-base: 1ms;
      --duration-slow: 1ms; --duration-spring: 1ms;
    }
    *, *::before, *::after {
      animation-duration: 1ms !important;
      animation-iteration-count: 1 !important;
      transition-duration: 1ms !important;
      scroll-behavior: auto !important;
    }
  }
}`);
w();

writeFileSync(join(root, "src", "tokens.css"), out.join("\n") + "\n");
const n = Object.keys(colour.ramps).length + Object.keys(colour.spectrum).filter((k) => !skip(k)).length;
console.log(`tokens.css written: ${n} ramps, ${Object.keys(scale.type).length} type steps, 3 densities`);
