// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/calendar" | "/checkin" | "/checkin/labels" | "/checkin/labels/print" | "/checkin/rooms/print" | "/checkin/station" | "/choose-church" | "/create-church" | "/dashboard" | "/design" | "/design/colour" | "/design/components" | "/design/icons" | "/design/motion" | "/design/space" | "/design/station" | "/design/type" | "/duplicates" | "/e/[slug]/[event]" | "/e/[slug]/[event]/register" | "/events" | "/events/[id]" | "/events/[id]/edit" | "/events/[id]/preview" | "/events/[id]/preview/register" | "/events/[id]/roster" | "/events/new" | "/f/[slug]/[form]" | "/f/[slug]/[form]/embed" | "/followups" | "/forms" | "/forms/[id]" | "/g/[slug]" | "/g/[slug]/[id]" | "/g/[slug]/embed" | "/groups" | "/groups/[id]" | "/groups/[id]/edit" | "/groups/new" | "/home" | "/home/household" | "/home/schedule" | "/import" | "/incidents" | "/join/[church]" | "/members" | "/members/[id]" | "/members/[id]/edit" | "/members/celebrations" | "/members/celebrations/print" | "/members/new" | "/members/print" | "/members/print/directory" | "/offline" | "/reports" | "/reports/attendance" | "/reports/build" | "/reports/custom/[id]" | "/reports/custom/[id]/print" | "/reports/growth" | "/reports/visitors" | "/reset" | "/schedule" | "/schedule/[id]" | "/schedule/[id]/schedule" | "/schedule/respond/[token]" | "/services" | "/services/[id]" | "/services/[id]/live" | "/services/[id]/plan" | "/services/[id]/plan/print" | "/serving/[[...rest]]" | "/settings" | "/settings/church" | "/settings/export" | "/settings/fields" | "/settings/followups" | "/settings/group-types" | "/settings/households" | "/settings/profile" | "/settings/roles" | "/settings/rooms" | "/settings/security" | "/settings/stations" | "/settings/tags" | "/settings/team" | "/settings/teams" | "/settings/website" | "/setup" | "/sign-in" | "/sign-up" | "/trust"
type AppRouteHandlerRoutes = "/api/export" | "/api/forms/file" | "/api/forms/upload" | "/api/upload" | "/auth/callback" | "/auth/sign-out" | "/events/[id]/export" | "/g/[slug]/[id]/join" | "/manifest.webmanifest" | "/reports/attendance/export" | "/reports/custom/[id]/export" | "/reports/custom/[id]/pptx" | "/reports/growth/export" | "/reports/visitors/export"
type PageRoutes = never
type LayoutRoutes = "/" | "/design" | "/settings"
type RedirectRoutes = "/people" | "/people/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/export": {}
  "/api/forms/file": {}
  "/api/forms/upload": {}
  "/api/upload": {}
  "/auth/callback": {}
  "/auth/sign-out": {}
  "/calendar": {}
  "/checkin": {}
  "/checkin/labels": {}
  "/checkin/labels/print": {}
  "/checkin/rooms/print": {}
  "/checkin/station": {}
  "/choose-church": {}
  "/create-church": {}
  "/dashboard": {}
  "/design": {}
  "/design/colour": {}
  "/design/components": {}
  "/design/icons": {}
  "/design/motion": {}
  "/design/space": {}
  "/design/station": {}
  "/design/type": {}
  "/duplicates": {}
  "/e/[slug]/[event]": { "slug": string; "event": string; }
  "/e/[slug]/[event]/register": { "slug": string; "event": string; }
  "/events": {}
  "/events/[id]": { "id": string; }
  "/events/[id]/edit": { "id": string; }
  "/events/[id]/export": { "id": string; }
  "/events/[id]/preview": { "id": string; }
  "/events/[id]/preview/register": { "id": string; }
  "/events/[id]/roster": { "id": string; }
  "/events/new": {}
  "/f/[slug]/[form]": { "slug": string; "form": string; }
  "/f/[slug]/[form]/embed": { "slug": string; "form": string; }
  "/followups": {}
  "/forms": {}
  "/forms/[id]": { "id": string; }
  "/g/[slug]": { "slug": string; }
  "/g/[slug]/[id]": { "slug": string; "id": string; }
  "/g/[slug]/[id]/join": { "slug": string; "id": string; }
  "/g/[slug]/embed": { "slug": string; }
  "/groups": {}
  "/groups/[id]": { "id": string; }
  "/groups/[id]/edit": { "id": string; }
  "/groups/new": {}
  "/home": {}
  "/home/household": {}
  "/home/schedule": {}
  "/import": {}
  "/incidents": {}
  "/join/[church]": { "church": string; }
  "/manifest.webmanifest": {}
  "/members": {}
  "/members/[id]": { "id": string; }
  "/members/[id]/edit": { "id": string; }
  "/members/celebrations": {}
  "/members/celebrations/print": {}
  "/members/new": {}
  "/members/print": {}
  "/members/print/directory": {}
  "/offline": {}
  "/people": {}
  "/people/[[...path]]": { "path"?: string[]; }
  "/reports": {}
  "/reports/attendance": {}
  "/reports/attendance/export": {}
  "/reports/build": {}
  "/reports/custom/[id]": { "id": string; }
  "/reports/custom/[id]/export": { "id": string; }
  "/reports/custom/[id]/pptx": { "id": string; }
  "/reports/custom/[id]/print": { "id": string; }
  "/reports/growth": {}
  "/reports/growth/export": {}
  "/reports/visitors": {}
  "/reports/visitors/export": {}
  "/reset": {}
  "/schedule": {}
  "/schedule/[id]": { "id": string; }
  "/schedule/[id]/schedule": { "id": string; }
  "/schedule/respond/[token]": { "token": string; }
  "/services": {}
  "/services/[id]": { "id": string; }
  "/services/[id]/live": { "id": string; }
  "/services/[id]/plan": { "id": string; }
  "/services/[id]/plan/print": { "id": string; }
  "/serving/[[...rest]]": { "rest"?: string[]; }
  "/settings": {}
  "/settings/church": {}
  "/settings/export": {}
  "/settings/fields": {}
  "/settings/followups": {}
  "/settings/group-types": {}
  "/settings/households": {}
  "/settings/profile": {}
  "/settings/roles": {}
  "/settings/rooms": {}
  "/settings/security": {}
  "/settings/stations": {}
  "/settings/tags": {}
  "/settings/team": {}
  "/settings/teams": {}
  "/settings/website": {}
  "/setup": {}
  "/sign-in": {}
  "/sign-up": {}
  "/trust": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/design": never
  "/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
