// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkin/labels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkin/labels">> = Specific
  const handler = {} as typeof import("../../app/checkin/labels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkin/labels/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkin/labels/print">> = Specific
  const handler = {} as typeof import("../../app/checkin/labels/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkin">> = Specific
  const handler = {} as typeof import("../../app/checkin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkin/rooms/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkin/rooms/print">> = Specific
  const handler = {} as typeof import("../../app/checkin/rooms/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkin/station/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkin/station">> = Specific
  const handler = {} as typeof import("../../app/checkin/station/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/choose-church/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/choose-church">> = Specific
  const handler = {} as typeof import("../../app/choose-church/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create-church/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-church">> = Specific
  const handler = {} as typeof import("../../app/create-church/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/colour/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/colour">> = Specific
  const handler = {} as typeof import("../../app/design/colour/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/components">> = Specific
  const handler = {} as typeof import("../../app/design/components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/icons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/icons">> = Specific
  const handler = {} as typeof import("../../app/design/icons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/motion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/motion">> = Specific
  const handler = {} as typeof import("../../app/design/motion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design">> = Specific
  const handler = {} as typeof import("../../app/design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/space/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/space">> = Specific
  const handler = {} as typeof import("../../app/design/space/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/station/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/station">> = Specific
  const handler = {} as typeof import("../../app/design/station/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design/type/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design/type">> = Specific
  const handler = {} as typeof import("../../app/design/type/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/duplicates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/duplicates">> = Specific
  const handler = {} as typeof import("../../app/duplicates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/e/[slug]/[event]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/e/[slug]/[event]">> = Specific
  const handler = {} as typeof import("../../app/e/[slug]/[event]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/e/[slug]/[event]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/e/[slug]/[event]/register">> = Specific
  const handler = {} as typeof import("../../app/e/[slug]/[event]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/preview">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/preview/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/preview/register">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/preview/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/roster/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[id]/roster">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/roster/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/new">> = Specific
  const handler = {} as typeof import("../../app/events/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/f/[slug]/[form]/embed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/f/[slug]/[form]/embed">> = Specific
  const handler = {} as typeof import("../../app/f/[slug]/[form]/embed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/f/[slug]/[form]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/f/[slug]/[form]">> = Specific
  const handler = {} as typeof import("../../app/f/[slug]/[form]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/followups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/followups">> = Specific
  const handler = {} as typeof import("../../app/followups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forms/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/[id]">> = Specific
  const handler = {} as typeof import("../../app/forms/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms">> = Specific
  const handler = {} as typeof import("../../app/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/g/[slug]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/g/[slug]/[id]">> = Specific
  const handler = {} as typeof import("../../app/g/[slug]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/g/[slug]/embed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/g/[slug]/embed">> = Specific
  const handler = {} as typeof import("../../app/g/[slug]/embed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/g/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/g/[slug]">> = Specific
  const handler = {} as typeof import("../../app/g/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/groups/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/groups/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/groups/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups/[id]">> = Specific
  const handler = {} as typeof import("../../app/groups/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/groups/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups/new">> = Specific
  const handler = {} as typeof import("../../app/groups/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups">> = Specific
  const handler = {} as typeof import("../../app/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/home/household/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home/household">> = Specific
  const handler = {} as typeof import("../../app/home/household/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/home/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home/schedule">> = Specific
  const handler = {} as typeof import("../../app/home/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import">> = Specific
  const handler = {} as typeof import("../../app/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents">> = Specific
  const handler = {} as typeof import("../../app/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/join/[church]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join/[church]">> = Specific
  const handler = {} as typeof import("../../app/join/[church]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/members/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/[id]">> = Specific
  const handler = {} as typeof import("../../app/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/celebrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/celebrations">> = Specific
  const handler = {} as typeof import("../../app/members/celebrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/celebrations/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/celebrations/print">> = Specific
  const handler = {} as typeof import("../../app/members/celebrations/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/new">> = Specific
  const handler = {} as typeof import("../../app/members/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members">> = Specific
  const handler = {} as typeof import("../../app/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/print/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/print/directory">> = Specific
  const handler = {} as typeof import("../../app/members/print/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/members/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/print">> = Specific
  const handler = {} as typeof import("../../app/members/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/attendance">> = Specific
  const handler = {} as typeof import("../../app/reports/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/build">> = Specific
  const handler = {} as typeof import("../../app/reports/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/custom/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/custom/[id]">> = Specific
  const handler = {} as typeof import("../../app/reports/custom/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/custom/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/custom/[id]/print">> = Specific
  const handler = {} as typeof import("../../app/reports/custom/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/growth">> = Specific
  const handler = {} as typeof import("../../app/reports/growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/visitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/visitors">> = Specific
  const handler = {} as typeof import("../../app/reports/visitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset">> = Specific
  const handler = {} as typeof import("../../app/reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/schedule/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule/[id]">> = Specific
  const handler = {} as typeof import("../../app/schedule/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/schedule/[id]/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../app/schedule/[id]/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/schedule/respond/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule/respond/[token]">> = Specific
  const handler = {} as typeof import("../../app/schedule/respond/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/[id]/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[id]/live">> = Specific
  const handler = {} as typeof import("../../app/services/[id]/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[id]">> = Specific
  const handler = {} as typeof import("../../app/services/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/[id]/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[id]/plan">> = Specific
  const handler = {} as typeof import("../../app/services/[id]/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/[id]/plan/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[id]/plan/print">> = Specific
  const handler = {} as typeof import("../../app/services/[id]/plan/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/serving/[[...rest]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/serving/[[...rest]]">> = Specific
  const handler = {} as typeof import("../../app/serving/[[...rest]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/church/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/church">> = Specific
  const handler = {} as typeof import("../../app/settings/church/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/export">> = Specific
  const handler = {} as typeof import("../../app/settings/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/fields">> = Specific
  const handler = {} as typeof import("../../app/settings/fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/followups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/followups">> = Specific
  const handler = {} as typeof import("../../app/settings/followups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/group-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/group-types">> = Specific
  const handler = {} as typeof import("../../app/settings/group-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/households/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/households">> = Specific
  const handler = {} as typeof import("../../app/settings/households/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/roles">> = Specific
  const handler = {} as typeof import("../../app/settings/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/rooms">> = Specific
  const handler = {} as typeof import("../../app/settings/rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/security">> = Specific
  const handler = {} as typeof import("../../app/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/stations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/stations">> = Specific
  const handler = {} as typeof import("../../app/settings/stations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/tags">> = Specific
  const handler = {} as typeof import("../../app/settings/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/team">> = Specific
  const handler = {} as typeof import("../../app/settings/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/teams">> = Specific
  const handler = {} as typeof import("../../app/settings/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/website/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/website">> = Specific
  const handler = {} as typeof import("../../app/settings/website/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trust">> = Specific
  const handler = {} as typeof import("../../app/trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forms/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forms/file">> = Specific
  const handler = {} as typeof import("../../app/api/forms/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forms/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forms/upload">> = Specific
  const handler = {} as typeof import("../../app/api/forms/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../app/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/events/[id]/export">> = Specific
  const handler = {} as typeof import("../../app/events/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/g/[slug]/[id]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/g/[slug]/[id]/join">> = Specific
  const handler = {} as typeof import("../../app/g/[slug]/[id]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manifest.webmanifest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/manifest.webmanifest">> = Specific
  const handler = {} as typeof import("../../app/manifest.webmanifest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/attendance/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/reports/attendance/export">> = Specific
  const handler = {} as typeof import("../../app/reports/attendance/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/custom/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/reports/custom/[id]/export">> = Specific
  const handler = {} as typeof import("../../app/reports/custom/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/custom/[id]/pptx/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/reports/custom/[id]/pptx">> = Specific
  const handler = {} as typeof import("../../app/reports/custom/[id]/pptx/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/growth/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/reports/growth/export">> = Specific
  const handler = {} as typeof import("../../app/reports/growth/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reports/visitors/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/reports/visitors/export">> = Specific
  const handler = {} as typeof import("../../app/reports/visitors/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/design/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/design">> = Specific
  const handler = {} as typeof import("../../app/design/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
